name: Clone and Push to New Repo

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GHL_TOKEN }}  # Your GitHub token stored securely

    steps:
      - name: Checkout empty workspace
        uses: actions/checkout@v4

      - name: Clone amd-aio-for-curser
        run: |
          git clone https://github.com/kishorkumartv000/amd-aio-for-curser main-repo

      - name: Copy tidal-dl-ng into main-repo
        run: |
          cd main-repo
          git clone https://github.com/exislow/tidal-dl-ng temp-tidal
          mv temp-tidal tidal-dl-ng
          rm -rf tidal-dl-ng/.git  # Remove inner .git so it's treated as normal files

      - name: Prepare and push to new repo
        run: |
          cd main-repo

          # Remove existing remote if present
          git remote remove origin || true

          # Reinitialize Git and configure identity
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch -M main

          # ✅ Push to your actual GitHub account
          NEW_REPO="clasidvegatea5241/combined-aio"

          git remote add origin https://x-access-token:${GH_TOKEN}@github.com/${NEW_REPO}.git
          git add .
          git commit -m "Initial commit with tidal-dl-ng folder"
          git push -u origin main
